version: "3.9"

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}

  cache:
    image: redis:latest
    restart: unless-stopped
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - db

  backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REQUEST_ORIGIN: ${REQUEST_ORIGIN}
      PORT: ${PORT}
    links:
      - db
      - cache
    depends_on:
      - db
      - cache

  frontend:
    build:
      context: ./example-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}

    depends_on:
      - backend
      - db
      - cache
