version: "3.9"

services:
  backend:
    build:
      context: ./example-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./example-backend/.env

  frontend:
    build:
      context: ./example-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - ./example-frontend/.env

    depends_on:
      - backend
